### PR TITLE
How To: Test with Capybara

### PR DESCRIPTION
**Pull request by lea927**
- [x] Adds Warden
- [x] Installs FactoryBot gem
- [x] Creates corresponding user factory on factories.rb file

[Setting up Warden](https://github.com/heartcombo/devise/wiki/How-To:-Test-with-Capybara)
[FactoryBot](https://github.com/thoughtbot/factory_bot)

### CODE REVIEW

**Comment by lea927** [comment]
Hi @yvettetan this is good to be pulled and tested on your local machine for merging. Let me know if updates are needed. Thanks!

**Review by yvettetan — CHANGES_REQUESTED** [review]
Please run rubocop.

**Review by yvettetan — APPROVED** [review]
Approved. Thanks lea!

**Comment by lea927** [comment]
> Approved. Thanks lea!

Cool - you may now pull from the master branch! :)

**Pull request merged**
